"""Credential-request guardrail — the agent may never ask for a secret.

The approved challenge flow confirms identity from things the bank already knows
about the customer: a date of birth, the last four digits of an Emirates ID. It
never asks the customer to *reveal* something that grants access — a PIN, a
password, a one-time passcode, a CVV, a full card number.

`prohibited_action` already applies a version of this test to the drafted
*recommendation*. This one applies it to the **reply**, and the distinction is
the reason the file exists. The recommendation is advice to a handler; the reply
is the sentence the customer actually hears, and on a voice call it is spoken
before any human sees it. It is also generated by a different code path — the
handler-turn prompt and the reply composer — which the output guardrails never
run over. A check that guards the advice but not the speech guards the wrong
half.

Two reasons this is a block and not a warning:

1. **It cannot be taken back.** A customer who has read their one-time passcode
   aloud has given it away, whatever the next sentence says.

2. **It trains the customer to be defrauded.** The single most effective
   protection a bank has against impersonation fraud is that a real bank never
   asks for these. An agent that asks — even once, even harmlessly, even to
   confirm something it already knows — spends that protection, and the customer
   who has learned that their bank sometimes asks is the customer who answers the
   next caller who does.

The check is deterministic, and it fails closed: an ambiguous match blocks.

**What it must not do** is block the sentence that says the right thing. "I will
never ask you for your PIN" and "don't share that code with anyone, not even
someone claiming to be us" are exactly the lines a fraud or collections call
should contain. So a match is cleared when the surrounding clause negates it or
frames it as a warning — the same shape of test `prohibited_action` uses, kept
separate here because the cue list is different: a warning is not merely a
negation.
"""
from __future__ import annotations

import re

from ..utils.types import GuardrailResult
from .base import Guardrail, GuardrailContext

# What must never be requested, and what to call it in the finding. Each pattern
# aims at the secret itself rather than at a phrasing of the request, because
# there are many ways to ask and only a few things worth asking for.
#
# Order is by specificity, not by severity — every one of these blocks. A
# one-time passcode is also a passcode and arguably a PIN, so it has to be
# recognised first; otherwise the finding reads "password" and the reviewer loses
# the distinction between a request for a static secret and a request for the
# live authentication code that is being used to move money right now.
_CREDENTIALS: list[tuple[re.Pattern, str]] = [
    (re.compile(r"\bo\.?t\.?p\b|\bone[\s-]?time\s+(?:password|passcode|code|pin)\b"
                r"|\bverification\s+code\b|\bauthentication\s+code\b"
                r"|\bcode\s+(?:we|I|the\s+bank)\s+(?:just\s+)?sent\b"
                r"|\bcode\s+(?:on|in)\s+your\s+(?:phone|message|sms)\b"
                r"|\bsms\s+code\b|\bsecure\s+code\b|\b3d[\s-]?secure\b",
                re.IGNORECASE),
     "one-time passcode"),
    (re.compile(r"\bp\.?i\.?n\b(?!\s*code\b)|\bpin\s*number\b", re.IGNORECASE),
     "PIN"),
    (re.compile(r"\bpass\s?word\b|\bpasscode\b(?!\s*we)", re.IGNORECASE),
     "password"),
    (re.compile(r"\bc\.?v\.?v\.?2?\b|\bcvc\b"
                r"|\b(?:three|3)\s+digits?\s+on\s+the\s+(?:back|reverse)\b"
                r"|\bsecurity\s+code\s+on\s+the\s+(?:back|card)\b", re.IGNORECASE),
     "card security code"),
    (re.compile(r"\bfull\s+card\s+number\b|\bcard\s+number\s+in\s+full\b"
                r"|\blong\s+number\s+on\s+(?:the|your)\s+card\b"
                r"|\b(?:sixteen|16)[\s-]digit\s+(?:card\s+)?number\b", re.IGNORECASE),
     "full card number"),
    (re.compile(r"\b(?:internet|online|mobile)\s+banking\s+(?:login|log[\s-]?in|"
                r"credentials|username\s+and\s+password)\b"
                r"|\busername\s+and\s+password\b", re.IGNORECASE),
     "banking login"),
]

# Cues that turn a mention into a warning or a refusal rather than a request.
# Broader than a plain negation list: "don't share", "no one from the bank will
# ask", "I won't need" and "keep it to yourself" are all the right thing to say
# and none of them is a simple "not".
_SAFE_FRAMING = re.compile(
    r"\b(?:never|not|n't|don't|do not|won't|will not|would not|wouldn't|"
    r"cannot|can't|no\s+one|nobody|no\s+genuine|any\s+caller|"
    r"refuse|refrain|avoid|without|instead\s+of|rather\s+than|"
    r"keep\s+(?:it|that|them)\s+to\s+yourself|share|disclose|reveal|"
    r"give\s+(?:it|that)\s+out|read\s+(?:it|that)\s+out\s+to)\b",
    re.IGNORECASE,
)

# How far back to look. Long enough for "I will never need to ask you for your
# one-time passcode", short enough that a negation two sentences earlier does not
# launder a request in this one.
_WINDOW = 90


def _clause_before(text: str, start: int) -> str:
    """The text back to the nearest clause boundary, capped at `_WINDOW`.

    Sentence boundaries matter here. "We would never ask for this. Now, what is
    your PIN?" must not read as safely framed, and it would if the window simply
    ran backwards a fixed number of characters.
    """
    window = text[max(0, start - _WINDOW):start]
    boundary = max(window.rfind("."), window.rfind(";"),
                   window.rfind("?"), window.rfind("!"))
    return window[boundary + 1:] if boundary != -1 else window


class CredentialRequestGuardrail(Guardrail):
    """Blocks any reply that solicits a credential from the customer."""

    name = "credential_request"
    severity = "block"

    def check(self, ctx: GuardrailContext) -> GuardrailResult:
        reply = ctx.reply or ""
        if not reply.strip():
            return self._ok("No reply to check.")

        found: list[dict[str, str]] = []
        for pattern, label in _CREDENTIALS:
            for match in pattern.finditer(reply):
                if _SAFE_FRAMING.search(_clause_before(reply, match.start())):
                    continue          # a warning about the credential, not a request
                found.append({"credential": label, "phrase": match.group(0)})
                break                 # one finding per credential is enough

        if not found:
            return self._ok("No credential requested.")

        names = ", ".join(sorted({f["credential"] for f in found}))
        return self._fail(
            f"The reply asks the customer for a credential ({names}). The approved "
            f"challenge flow never requires one, and asking teaches the customer to "
            f"answer an impersonator who does.",
            credentials=found,
        )
